### PR TITLE
feat(PE-3053): wallet domains table and pagination 

### PR DESCRIPTION
**Pull request by dtfiedler**
## Details
Related Task: [PE-3053](https://ardrive.atlassian.net/browse/PE-3053)
Completed Subtasks: 
- [PE-3054](https://ardrive.atlassian.net/browse/PE-3054)
- [PE-3055](https://ardrive.atlassian.net/browse/PE-3055)
- [PE-3058](https://ardrive.atlassian.net/browse/PE-3058)
- [PE-3062](https://ardrive.atlassian.net/browse/PE-3062)
- [PE-3063](https://ardrive.atlassian.net/browse/PE-3063)

[PE-3053]: https://ardrive.atlassian.net/browse/PE-3053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PE-3054]: https://ardrive.atlassian.net/browse/PE-3054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PE-3055]: https://ardrive.atlassian.net/browse/PE-3055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PE-3062]: https://ardrive.atlassian.net/browse/PE-3062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PE-3063]: https://ardrive.atlassian.net/browse/PE-3063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PE-3058]: https://ardrive.atlassian.net/browse/PE-3058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by atticusofsparta** [comment]
Manage buttons overflowing 
image

**Comment by atticusofsparta** [comment]
text overflow changing hieght of row
image

**Comment by atticusofsparta** [comment]
line is breaking early, could be adjusted to not break like this ( string shortening like we are using for txids used to be applied to this at 20 chars)
image

**Comment by atticusofsparta** [comment]
we have a mobile view for tables now: https://www.figma.com/file/q15ZCqGNGawabwhC60xzxJ/ArNS?node-id=2238%3A21658&t=Lgh7jsGVBt41oaJn-0 
image
ours : 
image

**Review by atticusofsparta — APPROVED** [review]

**Comment by dtfiedler** [comment]
addressed most comments and merged

**Pull request merged**
